version: '3'
services:
  nginx:
#    container_name: my_nginx
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx/html:/usr/share/nginx/html
    - ./nginx/conf:/etc/nginx
    - C:/Users/Daniel/GitHub/xc-edu/xc-ui-pc-static-portal:/etc/nginx/xc-ui-pc-static-portal
    privileged: true

  mysql:
#    container_name: my_mysql
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    #定义主机名
#    container_name: my_redis
    #使用的镜像
    image: redis:alpine
    #容器的映射端口
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    #定义挂载点
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/etc/conf
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    #环境变量
    privileged: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8

#Docker Networks
networks:
  app-network:
    driver: bridge
